/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        closeBotton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inicioText = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        passText = new javax.swing.JLabel();
        typeUser = new javax.swing.JTextField();
        separarUser = new javax.swing.JSeparator();
        typePassword = new javax.swing.JPasswordField();
        separarPass = new javax.swing.JSeparator();
        clicRecordar = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        iniciarBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        fondLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        closeBotton.setBackground(new java.awt.Color(255, 255, 255));
        closeBotton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        closeBotton.setForeground(new java.awt.Color(0, 0, 0));
        closeBotton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBotton.setText("X");
        closeBotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBotton.setOpaque(true);
        closeBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBottonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBottonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBottonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 970, Short.MAX_VALUE)
                .addComponent(closeBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeBotton, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        fondLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setOpaque(false);

        inicioText.setBackground(new java.awt.Color(255, 255, 255));
        inicioText.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        inicioText.setForeground(new java.awt.Color(255, 255, 255));
        inicioText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioText.setText("INICIO");
        inicioText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioTextMouseEntered(evt);
            }
        });

        userText.setBackground(new java.awt.Color(255, 255, 255));
        userText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userText.setForeground(new java.awt.Color(255, 255, 255));
        userText.setText("Usuario");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userTextMouseEntered(evt);
            }
        });

        passText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(255, 255, 255));
        passText.setText("Contraseña");

        typeUser.setBackground(new Color(0,0,0,0));
        typeUser.setForeground(Color.gray);
        typeUser.setText("Ingrese su usuario");
        typeUser.setBorder(null);
        typeUser.setOpaque(false);
        typeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeUserMouseClicked(evt);
            }
        });
        typeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUserActionPerformed(evt);
            }
        });

        separarUser.setBackground(new java.awt.Color(255, 255, 255));

        typePassword.setBackground(new Color(0,0,0,0));
        typePassword.setForeground(Color.gray);
        typePassword.setText("********");
        typePassword.setBorder(null);
        typePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typePasswordMouseClicked(evt);
            }
        });
        typePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typePasswordActionPerformed(evt);
            }
        });

        separarPass.setBackground(new java.awt.Color(255, 255, 255));

        clicRecordar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clicRecordar.setForeground(new java.awt.Color(255, 255, 255));
        clicRecordar.setText("Recordar");
        clicRecordar.setBorder(null);
        clicRecordar.setOpaque(false);
        clicRecordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicRecordarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ovide la Contraseña");

        iniciarBtn.setBackground(new java.awt.Color(255, 255, 255));
        iniciarBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        iniciarBtn.setForeground(new java.awt.Color(0, 0, 0));
        iniciarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciarBtn.setText("Iniciar");
        iniciarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarBtn.setOpaque(true);
        iniciarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarBtnMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No tengo una cuenta");

        register.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Registrate");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(inicioText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(separarUser)
                                .addComponent(passText)
                                .addComponent(separarPass)
                                .addComponent(typePassword)
                                .addComponent(userText)
                                .addComponent(typeUser, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clicRecordar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(inicioText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(userText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(separarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clicRecordar))
                .addGap(21, 21, 21)
                .addComponent(iniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register)
                    .addComponent(jLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        fondLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 280, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imag/Picsart_23-10-02_17-14-08-930.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        fondLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBottonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBottonMouseEntered
        // TODO add your handling code here:
        closeBotton.setBackground(Color.red);
        closeBotton.setForeground(Color.white);
        
    }//GEN-LAST:event_closeBottonMouseEntered

    private void closeBottonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBottonMousePressed
        // TODO add your handling code here:
        System.exit(0);      
    }//GEN-LAST:event_closeBottonMousePressed

    private void closeBottonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBottonMouseExited
        // TODO add your handling code here:
        closeBotton.setBackground(Color.white);
        closeBotton.setForeground(Color.black);
    }//GEN-LAST:event_closeBottonMouseExited

    private void inicioTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioTextMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inicioTextMouseEntered

    private void typeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeUserActionPerformed

    private void typeUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeUserMouseClicked
        // TODO add your handling code here:
        if(typeUser.getText().equals("Ingrese su usuario")){
            typeUser.setText("");
            typeUser.setForeground(Color.WHITE);
        }
        if(String.valueOf(typePassword.getPassword()).isEmpty()){
            typePassword.setText("********");
            typePassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeUserMouseClicked

    private void typePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePasswordMouseClicked
        // TODO add your handling code here:
        if(String.valueOf(typePassword.getPassword()).equals("********")){
            typePassword.setText("");
            typePassword.setForeground(Color.WHITE);
        }
        if(typeUser.getText().isEmpty()){
            typeUser.setText("Ingrese su usuario");
            typeUser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typePasswordMouseClicked

    private void clicRecordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicRecordarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clicRecordarActionPerformed

    private void iniciarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarBtnMouseEntered
        // TODO add your handling code here:
        iniciarBtn.setText("Inicia Ahora");
    }//GEN-LAST:event_iniciarBtnMouseEntered

    private void iniciarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarBtnMouseExited
        // TODO add your handling code here:
        iniciarBtn.setText("Iniciar");
    }//GEN-LAST:event_iniciarBtnMouseExited

    private void userTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseEntered
        // TODO add your handling code here
        
    }//GEN-LAST:event_userTextMouseEntered

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        // TODO add your handling code here:
        register.setForeground(Color.red);
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        // TODO add your handling code here:
        register.setForeground(Color.white);
    }//GEN-LAST:event_registerMouseExited

    private void iniciarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarBtnMouseClicked
        // TODO add your handling code here:
        if(typeUser.getText().equals("Ingrese su usuario") || typeUser.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }else if(String.valueOf(typePassword.getPassword()).equals("********") || String.valueOf(typePassword.getPassword()).isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: "+ typeUser.getText() + "\nContraseña: " + String.valueOf(typePassword.getPassword()), "LOGIN",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_iniciarBtnMouseClicked

    private void typePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox clicRecordar;
    private javax.swing.JLabel closeBotton;
    private javax.swing.JPanel fondLogin;
    private javax.swing.JLabel iniciarBtn;
    private javax.swing.JLabel inicioText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passText;
    private javax.swing.JLabel register;
    private javax.swing.JSeparator separarPass;
    private javax.swing.JSeparator separarUser;
    private javax.swing.JPasswordField typePassword;
    private javax.swing.JTextField typeUser;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
